create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.galactic_pilots (
  id uuid primary key default extensions.gen_random_uuid(),
  nickname text not null,
  pin_hash text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint galactic_pilot_nickname_length check (char_length(nickname) between 2 and 18),
  constraint galactic_pilot_pin_hash_present check (pin_hash is null or char_length(pin_hash) > 20)
);

create unique index if not exists galactic_pilots_nickname_unique
  on private.galactic_pilots ((lower(nickname)));

create table if not exists private.galactic_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  pilot_id uuid not null references private.galactic_pilots(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz not null default now()
);

create index if not exists galactic_sessions_pilot_idx
  on private.galactic_sessions (pilot_id, last_used_at desc);

create table if not exists private.galactic_rate_limits (
  id bigint generated by default as identity primary key,
  action text not null,
  subject_key text not null,
  requested_at timestamptz not null default now()
);

create index if not exists galactic_rate_limits_lookup_idx
  on private.galactic_rate_limits (action, subject_key, requested_at desc);

create table if not exists public.galactic_seasons (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint galactic_season_code_format check (code ~ '^v[0-9A-Za-z._-]{1,31}$'),
  constraint galactic_season_name_length check (char_length(name) between 3 and 80)
);

create table if not exists public.galactic_scores (
  season_code text not null references public.galactic_seasons(code) on delete cascade,
  pilot_id uuid not null references private.galactic_pilots(id) on delete cascade,
  distance integer not null default 0 check (distance between 0 and 2000000),
  checkpoints integer not null default 0 check (checkpoints between 0 and 100000),
  correct_answers integer not null default 0 check (correct_answers between 0 and 100000),
  destroyed integer not null default 0 check (destroyed between 0 and 100000),
  skin text not null default 'nebula' check (char_length(skin) between 1 and 32),
  trail text not null default 'pulse' check (char_length(trail) between 1 and 32),
  achieved_at timestamptz not null default now(),
  primary key (season_code, pilot_id)
);

create index if not exists galactic_scores_ranking_idx
  on public.galactic_scores (season_code, distance desc, correct_answers desc, destroyed desc, achieved_at asc);

alter table public.galactic_seasons enable row level security;
alter table public.galactic_scores enable row level security;

revoke all on table public.galactic_seasons from public, anon, authenticated;
revoke all on table public.galactic_scores from public, anon, authenticated;
revoke all on all tables in schema private from public, anon, authenticated;
revoke all on all sequences in schema private from public, anon, authenticated;

create or replace function private.clean_galactic_nickname(p_nickname text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select regexp_replace(btrim(coalesce(p_nickname, '')), '[[:space:]]+', ' ', 'g')
$$;

create or replace function private.request_fingerprint()
returns text
language plpgsql
stable
set search_path = pg_catalog, extensions
as $$
declare
  v_headers jsonb := '{}'::jsonb;
  v_ip text := 'unknown';
begin
  begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  exception when others then
    v_headers := '{}'::jsonb;
  end;
  v_ip := coalesce(nullif(btrim(split_part(coalesce(v_headers->>'x-forwarded-for', ''), ',', 1)), ''), 'unknown');
  return encode(extensions.digest(convert_to(v_ip, 'UTF8'), 'sha256'), 'hex');
end;
$$;

create or replace function private.enforce_galactic_rate_limit(
  p_action text,
  p_subject text,
  p_max_attempts integer,
  p_window interval
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
declare
  v_attempts integer;
begin
  delete from private.galactic_rate_limits
   where requested_at < now() - interval '24 hours';

  select count(*) into v_attempts
    from private.galactic_rate_limits
   where action = p_action
     and subject_key = p_subject
     and requested_at >= now() - p_window;

  if v_attempts >= p_max_attempts then
    raise exception using errcode = 'P0001', message = 'rate_limited';
  end if;

  insert into private.galactic_rate_limits(action, subject_key)
  values (p_action, p_subject);
end;
$$;

create or replace function private.new_galactic_session(p_pilot_id uuid)
returns text
language plpgsql
security definer
set search_path = pg_catalog, private, extensions
as $$
declare
  v_token text := encode(extensions.gen_random_bytes(32), 'hex');
begin
  insert into private.galactic_sessions(pilot_id, token_hash)
  values (
    p_pilot_id,
    encode(extensions.digest(convert_to(v_token, 'UTF8'), 'sha256'), 'hex')
  );
  return v_token;
end;
$$;

create or replace function public.claim_galactic_pilot(
  p_nickname text,
  p_pin text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private, extensions
as $$
declare
  v_nickname text := private.clean_galactic_nickname(p_nickname);
  v_pin text := nullif(p_pin, '');
  v_pilot private.galactic_pilots%rowtype;
  v_token text;
  v_created boolean := false;
  v_subject text := encode(extensions.digest(convert_to(lower(v_nickname), 'UTF8'), 'sha256'), 'hex');
begin
  if char_length(v_nickname) not between 2 and 18
     or v_nickname ~ '[[:cntrl:]<>]' then
    raise exception using errcode = 'P0001', message = 'invalid_nickname';
  end if;

  if v_pin is not null and char_length(v_pin) not between 4 and 8 then
    raise exception using errcode = 'P0001', message = 'invalid_pin_length';
  end if;

  select * into v_pilot
    from private.galactic_pilots
   where lower(nickname) = lower(v_nickname)
   for update;

  if not found then
    perform private.enforce_galactic_rate_limit(
      'register', private.request_fingerprint(), 80, interval '1 hour'
    );

    begin
      insert into private.galactic_pilots(nickname, pin_hash)
      values (
        v_nickname,
        case when v_pin is null then null
             else extensions.crypt(v_pin, extensions.gen_salt('bf', 10))
        end
      )
      returning * into v_pilot;
      v_created := true;
    exception when unique_violation then
      raise exception using errcode = 'P0001', message = 'nickname_taken';
    end;
  else
    if v_pilot.pin_hash is null then
      raise exception using errcode = 'P0001', message = 'nickname_taken';
    end if;

    perform private.enforce_galactic_rate_limit(
      'unlock', v_subject, 8, interval '10 minutes'
    );

    if v_pin is null then
      raise exception using errcode = 'P0001', message = 'pin_required';
    end if;
    if extensions.crypt(v_pin, v_pilot.pin_hash) <> v_pilot.pin_hash then
      raise exception using errcode = 'P0001', message = 'pin_invalid';
    end if;
  end if;

  v_token := private.new_galactic_session(v_pilot.id);
  update private.galactic_pilots set last_seen_at = now() where id = v_pilot.id;

  return jsonb_build_object(
    'nickname', v_pilot.nickname,
    'token', v_token,
    'protected', v_pilot.pin_hash is not null,
    'created', v_created
  );
end;
$$;

create or replace function public.get_galactic_leaderboard(
  p_season text,
  p_limit integer default 10
)
returns table (
  rank_position bigint,
  nickname text,
  distance integer,
  checkpoints integer,
  correct_answers integer,
  destroyed integer,
  skin text,
  trail text,
  achieved_at timestamptz
)
language sql
stable
security definer
set search_path = pg_catalog, public, private
as $$
  select
    row_number() over (
      order by s.distance desc, s.correct_answers desc, s.destroyed desc, s.achieved_at asc
    ) as rank_position,
    p.nickname,
    s.distance,
    s.checkpoints,
    s.correct_answers,
    s.destroyed,
    s.skin,
    s.trail,
    s.achieved_at
  from public.galactic_scores s
  join private.galactic_pilots p on p.id = s.pilot_id
  where s.season_code = p_season
  order by s.distance desc, s.correct_answers desc, s.destroyed desc, s.achieved_at asc
  limit greatest(1, least(coalesce(p_limit, 10), 50))
$$;

create or replace function public.submit_galactic_score(
  p_token text,
  p_season text,
  p_season_name text,
  p_distance integer,
  p_checkpoints integer,
  p_correct integer,
  p_destroyed integer,
  p_skin text default 'nebula',
  p_trail text default 'pulse'
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private, extensions
as $$
declare
  v_pilot_id uuid;
  v_position bigint;
  v_rows integer := 0;
begin
  if p_token is null or char_length(p_token) <> 64 then
    raise exception using errcode = 'P0001', message = 'invalid_session';
  end if;
  if p_season !~ '^v[0-9A-Za-z._-]{1,31}$'
     or char_length(p_season_name) not between 3 and 80 then
    raise exception using errcode = 'P0001', message = 'invalid_season';
  end if;
  if p_distance not between 0 and 2000000
     or p_checkpoints not between 0 and 100000
     or p_correct not between 0 and 100000
     or p_destroyed not between 0 and 100000
     or p_correct > p_checkpoints
     or char_length(coalesce(p_skin, '')) not between 1 and 32
     or char_length(coalesce(p_trail, '')) not between 1 and 32 then
    raise exception using errcode = 'P0001', message = 'invalid_score';
  end if;

  select pilot_id into v_pilot_id
    from private.galactic_sessions
   where token_hash = encode(extensions.digest(convert_to(p_token, 'UTF8'), 'sha256'), 'hex')
     and last_used_at >= now() - interval '1 year'
   for update;

  if not found then
    raise exception using errcode = 'P0001', message = 'invalid_session';
  end if;

  perform private.enforce_galactic_rate_limit('score', v_pilot_id::text, 60, interval '1 hour');

  update private.galactic_sessions
     set last_used_at = now()
   where token_hash = encode(extensions.digest(convert_to(p_token, 'UTF8'), 'sha256'), 'hex');

  insert into public.galactic_seasons(code, name)
  values (p_season, p_season_name)
  on conflict (code) do nothing;

  insert into public.galactic_scores(
    season_code, pilot_id, distance, checkpoints, correct_answers,
    destroyed, skin, trail, achieved_at
  )
  values (
    p_season, v_pilot_id, p_distance, p_checkpoints, p_correct,
    p_destroyed, p_skin, p_trail, now()
  )
  on conflict (season_code, pilot_id) do update
    set distance = excluded.distance,
        checkpoints = excluded.checkpoints,
        correct_answers = excluded.correct_answers,
        destroyed = excluded.destroyed,
        skin = excluded.skin,
        trail = excluded.trail,
        achieved_at = excluded.achieved_at
  where excluded.distance > public.galactic_scores.distance
     or (excluded.distance = public.galactic_scores.distance
         and excluded.correct_answers > public.galactic_scores.correct_answers)
     or (excluded.distance = public.galactic_scores.distance
         and excluded.correct_answers = public.galactic_scores.correct_answers
         and excluded.destroyed > public.galactic_scores.destroyed);

  get diagnostics v_rows = row_count;

  select ranked.rank_position into v_position
  from (
    select
      pilot_id,
      row_number() over (
        order by distance desc, correct_answers desc, destroyed desc, achieved_at asc
      ) as rank_position
    from public.galactic_scores
    where season_code = p_season
  ) ranked
  where ranked.pilot_id = v_pilot_id;

  return jsonb_build_object('position', v_position, 'updated', v_rows > 0);
end;
$$;

revoke all on function public.claim_galactic_pilot(text, text) from public;
revoke all on function public.get_galactic_leaderboard(text, integer) from public;
revoke all on function public.submit_galactic_score(text, text, text, integer, integer, integer, integer, text, text) from public;

grant execute on function public.claim_galactic_pilot(text, text) to anon, authenticated;
grant execute on function public.get_galactic_leaderboard(text, integer) to anon, authenticated;
grant execute on function public.submit_galactic_score(text, text, text, integer, integer, integer, integer, text, text) to anon, authenticated;
